MAIN_DIR = src

.PHONY: main

all: main

main:
	$(MAKE) -C $(MAIN_DIR)

cleandep:
	$(MAKE) -C $(MAIN_DIR) cleandep
	
clean:
	$(MAKE) -C $(MAIN_DIR) clean

run-main:
	$(MAKE) -C $(MAIN_DIR) run
